nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: false
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^http(s)?://(localhost|127.0.0.1|172\.18\.0\.[0-9]+)(:[0-9]+)?$']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            allow_credentials: true
            max_age: 3600
